runtime: python39

handlers:
  - url: /
    static_files: index.html
    upload: index.html
    secure: always

  - url: /app.js
    static_files: app.js
    upload: app.js

  - url: /app.css
    static_files: app.css
    upload: app.css
